name: Build and Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Cache node_modules
        id: cache_node_modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            package-lock.json
          key: ${{ runner.os }}-${{ hashFiles('package.json') }}

      - name: Use Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Install dependencies
        if: steps.cache_node_modules.outputs.cache-hit != 'true'
        run: |
          npm i

      - name: Build
        run: npm run build

      - name: Deploy to Github Pages
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vuepress/dist/
          publish_branch: vuepress_pages
          force_orphan: true
          cname: 'ml.akasaki.space'

  check_path:
    name: Check file paths for Windows
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Check file paths
        run: |
          find | grep '[\\\\<>:"|?*]' && exit 1 || exit 0
